/** This file generated by @midwayjs/bundle-helper */

export { MainConfiguration as Configuration } from './configuration';
export * from './config/config.default';
export * from './config/config.local';
export * from './interface';
